# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sass_compile_file <- function(filename_arg, options = NULL) {
    .Call(`_sassr_sass_compile_file`, filename_arg, options)
}

